kafka.bootstrap-servers=${BOOTSTRAP_SERVER_URL:localhost:9092}
kafka.maximum.retry.attempts=5
kafka.retry.throttle.rate.milliseconds=1000
kafka.consumer.concurrency=${CONCURRENT_LISTENER_INSTANCES:1}
kafka.message.send.topic=${FILING_RECEIVED_TOPIC:filing-received}
kafka.message.receive.topic=${TX_CLOSED:tx-closed}
kafka.message.group.name=${GROUP_ID:filing-resource-handler}
management.endpoints.enabled-by-default=false
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true
management.health.mongo.enabled=false
internal.api-key=${CHS_INTERNAL_API_KEY}
internal.api-url=${CHS_INTERNAL_API_URL}
timeout.milliseconds=${TIMEOUT_MILLISECONDS:0}
oauth2.client.id=${OAUTH2_CLIENT_ID:client}
api.local.url=${API_LOCAL_URL}